# Import configuration
source = ~/.config/monitor.conf
source = ~/.config/variables.conf
source = ~/.config/autostart.conf
source = ~/.config/env.conf
source = ~/.config/permissions.conf
source = ~/.config/appearance.conf
source = ~/.config/input.conf
source = ~/.config/keybindings.conf
source = ~/.config/windowrules.conf

# ...
